---
- hosts: all
  become: true
  tasks:

  - name: Install apache2 and support for php
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
